### ISSUE TITLE
Roadmap to the MVP

### ISSUE THREAD

**Issue by verdie-g** [verdie-g/crpg#166]
- [x] Login with Steam
- [x] Create characters
- [x] Gain experience/gold by playing
- [x] Increase characters stats
- [x] Stats in-game
- [x] Buy items
- [x] Equip items
- [x] Retiring
- [x] Modify items in-game
- [x] Respecialization (redistribute your stats for an experience penalty)
- [x] Multiple characters
- [x] Clan creation
- [x] Clan invitation
- [x] Clan joining
- [x] Clan members management
- [x] Game servers
